version: '3.7'

services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8060:8080"
    restart: always
    environment:
      - SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD
      # - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/thunder_db
      # - SPRING_DATASOURCE_USERNAME=postgres
      # - SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - thundershare

  client:
    build:
      context: ./portal/client
      dockerfile: Dockerfile
    ports:
      - "8070:80"
    restart: always
    depends_on:
      - api
    networks:
      - thundershare

networks:
  thundershare: