server:
  port: 8080
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    change-log: classpath:db/db.changelog-master.xml
    enabled: true
    drop-first: false
    check-change-log-location: true
    default-schema: sc_thunder
    database-change-log-table: thunder_db

  logging:
    level:
      org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR
      com.shimunmatic.thundershare: TRACE